/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2018-04-26.dbd8897"
#define SSHVER "PuTTY-Snapshot-2018-04-26.dbd8897"
#define BINARY_VERSION 0,70,1296,0
#define SOURCE_COMMIT "dbd88975f2d4c3d1573c45b785ab5669690027c6"
